### ISSUE TITLE
how to encode job steps using the dsl

### ISSUE THREAD

**Issue by eitansuez** [jhmcstanton/rudder#9]
hi jim,
 glad to see your project.  i'm playing with rudder to see if i can model a sample pipeline with it.
 i'm able to build my resource types and resources just fine, with the docs guiding me.
 but i'm struggling to figure how how to encode a job.  it seems the dsl does not define 
 classes for plans, aggregate steps, gets, puts, and task steps.  perhaps it's just me, or
 perhaps i need a few more complex examples as a guide to help me figure out how to 
 encode jobs.  anyhow, i really appreciate your project and hope that i can transition from
 using raw yaml to using rudder, if i manage to generate my yamls using your dsl.
thanks,
/ eitan

**Comment by eitansuez** [comment]
ok, i think i'm getting it.  it's just pure data all the way down inside the jobs.

**Comment by jhmcstanton** [comment]
Hi Eitan, 

Sounds like you are getting yourself pretty well sorted out, glad to hear it. Have you had a chance to check out the [examples in the repo](https://github.com/jhmcstanton/rudder/tree/master/examples) ?

[hello_world](https://github.com/jhmcstanton/rudder/blob/master/examples/hello_world_pipeline.rb) includes `in_parallel` (which replaced `aggregate`, you should be able to just substitute one for the other based on your concourse version) as well simple inline tasks and jobs.

[includes](https://github.com/jhmcstanton/rudder/tree/master/examples/includes) has some more sophisticated ways to create and manage jobs and resources by splitting them out into their own files and including them into your pipeline.

> ok, i think i'm getting it. it's just pure data all the way down inside the jobs.

Yup, `rudder`'s attempts to add sugar to top level concourse primitives (resources, resource types, jobs, groups, and the pipeline itself) while remaining agnostic of the internal fields which are subject to frequent change across concourse versions. 

Let me know if that helps!

**Comment by eitansuez** [comment]
yes, thank you.  i'll let you know how things are coming along after i've managed to port a couple of pipelines over.

**Comment by eitansuez** [comment]
i can't figure out how to set serial = true on a job.  or anything job property that is not part of / outside the plan

**Comment by jhmcstanton** [comment]
When defining primitives like jobs or resources rudder allows the user to add arbitrary fields into the primitive by calling those fields as methods.

For example:

```ruby
job :cool_new_job do
  plan << { get: :my_git_repo, trigger: true }
  serial true # Alternatively, this can be serial(true)
end
```

Here is another example I made by tweaking the hello world pipeline
[hello_world_pipeline.rb](https://github.com/jhmcstanton/rudder/files/4106314/hello_world_pipeline.rb.txt)
[pipeline.yml](https://github.com/jhmcstanton/rudder/files/4106313/pipeline.yml.txt)

Side note, apparently github does not support uploading arbitrary file types so these are txts :man_facepalming:

**Comment by eitansuez** [comment]
got it. thanks! / eitan

**Comment by eitansuez** [comment]
ok, another question.. i have many jobs with common plan bits that i'd like to refactor.  i've tried writing a method that i just call to add the common elements to my plan, but i can't get it to work.  i suspect anything i try to call from inside a job block goes to method_missing.  trying to figure out how to call a method i define in the outer scope of my script from inside a job block.

**Comment by eitansuez** [comment]
ok, figured it out.  sorry it was in your example.  via the pipeline block param i can access the outer scope.  got it.  sorry.

**Comment by jhmcstanton** [comment]
No problem! Did you figure out the job encoding alright? Any other questions?

**Comment by eitansuez** [comment]
everything's coming along swimmingly!  my pipelines are in such a better shape now thanks to you and this rudder project.  not yet done applying rudder but happy to say goodbye to editing yaml files to set pipelines.

**Comment by jhmcstanton** [comment]
Fantastic! In that case I'm going to go ahead and close this issue but feel free to open another if you have any other questions or concerns.
